app:
  message: message succesfuly sent

spring:
  rabbitmq:
    host: localhost
    password: guest
    port: 15672
    username: guest
    exchange: user.exchange
    queue: user.queue
    authqueue: auth.queue
    routingkey: user.routingkey