app:
  message: message succesfuly sent

spring:
  rabbitmq:
    host: localhost
    password: guest
    port: 15672
    username: guest
    exchange: user.exchange
    queue: userqueue
    authqueue: authqueue
    tokenqueue: tokenqueue
    routingkey: userkey
    authroutingkey: authkey
    tokenroutingkey: tokenkey